export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAIL = "REGISTER_FAIL";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";
export const USER_LOADED = "USER_LOADED";
export const AUTH_ERROR = "AUTH_ERROR";
export const LOG_OUT = "LOG_OUT";
export const SET_REQUEST_LOADING = "REQUEST_LOADING";

export const GET_DECKS = "GET_DECKS";
export const ADD_DECK = "ADD_DECK";
export const UPDATE_DECK = "UPDATE_DECK";
export const DELETE_DECK = "DELETE_DECK";
export const GET_REVIEW_FLASHCARDS = "GET_REVIEW_FLASHCARDS";

export const GET_FLASHCARDS = "GET_FLASHCARDS";
export const UPDATE_FLASHCARDS = "UPDATE_FLASHCARDS";
export const REMOVE_FLASHCARDS = "REMOVE_FLASHCARDS";

export const ADD_NEW_FLASHCARD = "ADD_NEW_FLASHCARD";
export const UPDATE_EXISTING_FLASHCARD = "UPDATE_EXISTING_FLASHCARD";

export const GET_DECKS_FLASHCARDS = "GET_DECKS_FLASHCARDS";
export const REMOVE_DECKS_FLASHCARDS = "REMOVE_DECKS_FLASHCARDS";

export const SET_ALERT = "SET_ALERT";
export const REMOVE_ALERT = "REMOVE ALERT";
export const RESET_ALERTS = "RESET_ALERTS";
